apiVersion: v2
name: laravel
description: Laravel Helm Chart
version: 1.0.0
dependencies:
- name: generic
  version: 1.3.5
  repository: "file://../generic"
- name: mysql
  version: 1.0.0
  repository: "file://../mysql"
- name: redis
  version: 1.0.0
  repository: "file://../redis"
