apiVersion: v2
name: laravel
description: Laravel Helm Chart
version: 1.2.0
dependencies:
- name: generic
  version: 1.5.0
  repository: https://fireworkweb.github.io/charts
- name: mysql
  condition: mysql.enabled
  version: 1.1.4
  repository: https://fireworkweb.github.io/charts
- name: redis
  condition: redis.enabled
  version: 1.1.4
  repository: https://fireworkweb.github.io/charts
