apiVersion: v2
name: laravel
description: Laravel Helm Chart
version: 1.1.5
dependencies:
- name: generic
  version: 1.4.3
  repository: https://fireworkweb.github.io/charts
- name: mysql
  condition: mysql.enabled
  version: 1.1.3
  repository: https://fireworkweb.github.io/charts
- name: redis
  condition: redis.enabled
  version: 1.1.3
  repository: https://fireworkweb.github.io/charts
