mysql:
  enabled: true

  generic:
    # strategy:
    #   type: Recreate
    containers:
      default:
        args: ["--default-authentication-plugin=mysql_native_password"]

    services:
      default:
        fullName: mysql

redis:
  enabled: true

  generic:
    # strategy:
    #   type: Recreate
    services:
      default:
        fullName: redis

generic:
  # imagePullSecrets:
  #   - name: # REQUIRED VALUE #
  # strategy:
  #   type: Recreate

  initContainers:
    5-migrate:
      enabled: true
      image:
        repository: # REQUIRED VALUE #
        pullPolicy: Always
        tag: # REQUIRED VALUE #
      args: ["php", "artisan", "migrate:fresh", "--force", "--step", "--seed"]
      envFrom:
        - secretRef:
            name: env

  containers:
    app:
      image:
        repository: # REQUIRED VALUE #
        pullPolicy: Always
        tag: # REQUIRED VALUE #
      envFrom:
        - secretRef:
            name: env
    http:
      image:
        repository: # REQUIRED VALUE #
        pullPolicy: Always
        tag: # REQUIRED VALUE #
      envFrom:
        - secretRef:
            name: env
    worker:
      # enabled: true
      image:
        repository: # REQUIRED VALUE #
        pullPolicy: Always
        tag: # REQUIRED VALUE #
      envFrom:
        - secretRef:
            name: env

  cronjobs:
    schedule:
      # enabled: true
      concurrencyPolicy: Allow
      schedule: "* * * * *"
      restartPolicy: Never
      image:
        repository: # REQUIRED VALUE #
        pullPolicy: Always
        tag: # REQUIRED VALUE #
      envFrom:
        - secretRef:
            name: env

  secrets:
    - name: env
      data:
        APP_NAME: "Laravel Example"
        APP_ENV: "develop"
        APP_KEY: # REQUIRED VALUE #
        APP_DEBUG: "true"
        APP_URL: # REQUIRED VALUE #
        LOG_CHANNEL: "stderr"
        DB_HOST: "mysql"
        DB_PORT: "3306"
        DB_DATABASE: "database"
        DB_USERNAME: "user"
        DB_PASSWORD: "pass"
        CACHE_DRIVER: "redis"
        QUEUE_CONNECTION: "redis"
        SESSION_DRIVER: "redis"
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"

  ingresses:
    - hosts:
        - host: # REQUIRED VALUE #
          paths:
            - serviceName: default
              servicePort: 80
      # annotations:
      #   kubernetes.io/ingress.class: nginx
      # tls:
      #   - secretName: # REQUIRED VALUE #
      #     hosts:
      #       - # REQUIRED VALUE #
