apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}
  labels: {{ include "generic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{ include "generic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "generic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- range $value := .Values.initContainers }}
        - name: {{ $value.name }}
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          {{- with $value.command }}
          command: {{ . | toJson }}
          {{- end }}
          {{- with $value.args }}
          args: {{ . | toJson }}
          {{- end }}
          {{- with $value.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        {{- range $value := .Values.containers }}
        - name: {{ $value.Name }}
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: {{ $value.image.pullPolicy }}
          ports: {{ toYaml $value.ports | nindent 12 }}
          livenessProbe: {{ toYaml $value.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml $value.readinessProbe | nindent 12 }}
          {{- with $value.command }}
          command: {{ . | toJson }}
          {{- end }}
          {{- with $value.args }}
          args: {{ . | toJson }}
          {{- end }}
          {{- with $value.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $value.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
