{{- if .Values.secrets }}
{{- $fullName := include "generic.fullname" . -}}
{{- $labels := include "generic.labels" . -}}
{{- range $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}-{{ $secret.name }}"
  labels: {{ $labels | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
