apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  labels: {{ include "generic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector: {{ include "generic.selectorLabels" . | nindent 4 }}
