apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-http
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-http
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: http
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
data:
    default.conf: |
        server {
            listen 80 default_server;
            server_name _;
            root /app/public;
            index index.html index.htm index.php;
            charset utf-8;

            location = /favicon.ico { log_not_found off; access_log off; }
            location = /robots.txt  { log_not_found off; access_log off; }

            client_max_body_size 25M;

            error_page 404 /index.php;

            location / {
                try_files $uri /index.php$is_args$args;
            }

            location ~ \.php$ {
                add_header X-Served-By FWD;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_pass {{ .Release.Name }}-app:{{ .Values.app.port }};
            }

            location ~ /\.ht {
                deny all;
            }
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-http
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-http
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: http
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.http.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}-http
        app.kubernetes.io/version: {{ .Values.version | quote }}
        app.kubernetes.io/component: http
        helm.sh/chart: {{ .Chart.Name }}
        helm.sh/chart-version: {{ .Chart.Version }}
    spec:
      {{- with .Values.http.image.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: http
          image: "{{ .Values.http.image.repository }}:{{ .Values.http.image.tag }}"
          imagePullPolicy: {{ .Values.http.image.pullPolicy | default "IfNotPresent" }}
          {{- with .Values.http.command }}
          command: {{ . | toJson }}
          {{- end }}
          {{- with .Values.http.args }}
          args: {{ . | toJson }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.http.port }}
          {{- if hasKey .Values.http "livenessProbe" }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- else }}
          livenessProbe:
            tcpSocket:
                port: {{ .Values.http.port }}
          {{- end }}
          {{- if hasKey .Values.http "readinessProbe" }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- else }}
          readinessProbe:
            tcpSocket:
                port: {{ .Values.http.port }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
            {{- if .Values.storage.enabled }}
            - name: volume
              mountPath: {{ .Values.storage.mountPath }}
            {{- end }}
          {{- with .Values.http.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-http
        {{- if .Values.storage.enabled }}
        - name: volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-storage
        {{- end }}
      {{- with .Values.http.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.http.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.http.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-http
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: http
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-http
