{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-migrate
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: migrate
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-migrate
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}-migrate
        app.kubernetes.io/version: {{ .Values.version | quote }}
        app.kubernetes.io/component: migrate
        helm.sh/chart: {{ .Chart.Name }}
        helm.sh/chart-version: {{ .Chart.Version }}
    spec:
      {{- with .Values.app.image.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          args: {{ .Values.migrate.args | toJson }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
          {{- if .Values.storage.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.storage.mountPath }}
              name: volume
          {{- end }}
      {{- if .Values.storage.enabled }}
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-storage
      {{- end }}
{{- end }}
