apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-worker
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: worker
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}-worker
        app.kubernetes.io/version: {{ .Values.version | quote }}
        app.kubernetes.io/component: worker
        helm.sh/chart: {{ .Chart.Name }}
        helm.sh/chart-version: {{ .Chart.Version }}
    spec:
      {{- with .Values.worker.image.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy | default "IfNotPresent" }}
          {{- if hasKey .Values.worker "command" }}
          command: {{ . | toJson }}
          {{- else }}
          command: ["php", "artisan", "horizon"]
          {{- end }}
          {{- with .Values.worker.args }}
          args: {{ . | toJson }}
          {{- end }}
          {{- if hasKey .Values.worker "livenessProbe" }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- else }}
          # livenessProbe:
          #   tcpSocket:
          #       port: {{ .Values.worker.port }}
          {{- end }}
          {{- if hasKey .Values.worker "readinessProbe" }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- else }}
          # readinessProbe:
          #   tcpSocket:
          #       port: {{ .Values.worker.port }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
          {{- if .Values.storage.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.storage.mountPath }}
              name: volume
          {{- end }}
          {{- with .Values.worker.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.storage.enabled }}
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-storage
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
