{{- if .Values.ingresses }}
{{- $fullName := include "generic.fullname" . -}}
{{- $labels := include "generic.labels" . -}}
{{- range $ingress := .Values.ingresses }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}-{{ .name }}"
  labels: {{ $labels | nindent 4 }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/" }}
            backend:
              serviceName: "{{ $fullName }}-{{ .serviceName }}"
              servicePort: {{ .servicePort }}
          {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
