{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-database
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: database
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}-database
        app.kubernetes.io/version: {{ .Values.version | quote }}
        app.kubernetes.io/component: database
        helm.sh/chart: {{ .Chart.Name }}
        helm.sh/chart-version: {{ .Chart.Version }}
    spec:
      {{- with .Values.database.image.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: database
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy | default "IfNotPresent" }}
          {{- with .Values.database.command }}
          command: {{ . | toJson }}
          {{- end }}
          {{- with .Values.database.args }}
          args: {{ . | toJson }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.database.port }}
          {{- if hasKey .Values.database "livenessProbe" }}
          livenessProbe: {{ toYaml .Values.database.livenessProbe | nindent 12 }}
          {{- else }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.database.port }}
          {{- end }}
          {{- if hasKey .Values.database "readinessProbe" }}
          readinessProbe: {{ toYaml .Values.database.readinessProbe | nindent 12 }}
          {{- else }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.database.port }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-database-env
          volumeMounts:
            - name: volume
              mountPath: /var/lib/mysql
              subPath: mysql
          {{- with .Values.database.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-database-volume
      {{- with .Values.database.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-database-volume
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-database-volume
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: database-volume
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
spec:
  {{- if hasKey .Values.database.storage "className" }}
  storageClassName: {{ .Values.database.storage.className }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-env
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-database-env
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: database-env
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
type: Opaque
data:
  {{- range $key, $value := .Values.database.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-database
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: database
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-database
{{- end }}
